### ISSUE TITLE
Ruby exception on simple run [SOLVED]

### ISSUE THREAD

**Issue by matandobr** [hahwul/droid-hunter#10]
This is happening on macOS 
$ ruby dhunter.rb 
`/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
/Library/Ruby/Gems/2.0.0/gems/html-table-1.4.2/lib/html/table.rb:8:in `<top (required)>': superclass must be a Class (Module given) (TypeError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Users/matandobr/repos/droid-hunter/src/generate_report.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from dhunter.rb:3:in `<main>'`

**Comment by matandobr** [comment]
solved after installing html-table gem

**Comment by hahwul** [comment]
I am glad that the issue has been resolved. Please let me know if you have any questions.

`gem install html-table`
