### ISSUE TITLE
`popen': No such file or directory

### ISSUE THREAD

**Issue by hexrom** [hahwul/droid-hunter#12]
Ran into this error trying to run the tool against an APK I am testing, using a Mac. 

dhunter.rb:51:in `popen': No such file or directory - /usr/bin/aapt (Errno::ENOENT)
	from dhunter.rb:51:in `scan_info'
	from dhunter.rb:165:in `<main>'

Read elsewhere that a possible mitigation may be to try and add an extra parameter 'shell=True' to the Popen call. Any insight on this issue?

**Comment by hahwul** [comment]
@RxSec 
I think this problem is not installed aapt.

In my memory, it seems that the android tool did not include aapt from macos.
(brew install case)

If you place aapt at the bottom of the / usr / bin directory, the issue is likely to be resolved.

**Comment by hahwul** [comment]
@RxSec 
**[case macos]**
1. Download aapt binary
https://github.com/eladkarako/aapt-pre-build-binary

2. edit config.rb file (./config/config.rb)
```
# Tool path
$p_adb = "/usr/bin/adb"
$p_aapt = "/usr/bin/aapt"  # aapt binary path
```

**[to-do]**
 - Import aapt, adb binary this project.
 - Update README.md

Thank you :)
